// src/services/extractSkill.js

// =====================================================
// 1. DÁN DANH SÁCH SKILL VÀO ĐÂY
// =====================================================
const SKILLS = [
  "1 kim",
  "2 kim",
  "2d/3d design",
  "3 kim",
  "3d modeling",
  "3ds max",
  "4 kim",
  "5s",
  "account management",
  "after effects",
  "agile",
  "an ninh mạng",
  "an ninh thông tin",
  "an toàn thông tin",
  "android",
  "angular",
  "animation",
  "antivirus",
  "api",
  "audit",
  "autocad",
  "automation testing",
  "aws",
  "azure",
  "b2b",
  "ba",
  "backend",
  "bim",
  "biên dịch",
  "biên tập",
  "blockchain",
  "blue team",
  "botox",
  "branding",
  "bán hàng",
  "bán tour",
  "báo cáo tài chính",
  "bóc tách khối lượng",
  "bảo trì máy móc",
  "bảo trì điện",
  "c#",
  "c&b",
  "c++",
  "cad/cam",
  "call center",
  "cam",
  "capa",
  "capcut",
  "catia",
  "chiller",
  "chăm sóc bệnh nhân",
  "chăm sóc da",
  "chăm sóc khách hàng",
  "chỉnh sửa video",
  "chỉnh sửa ảnh",
  "cloud",
  "cnc",
  "computer vision",
  "content creation",
  "content creator",
  "content marketing",
  "copywriting",
  "cost accounting",
  "creo",
  "crm",
  "css",
  "cyber security",
  "cơ khí",
  "cấy mô",
  "cắt may",
  "cắt vải",
  "dashboard",
  "deep learning",
  "devops",
  "di truyền học",
  "digital marketing",
  "django",
  "docker",
  "dược lâm sàng",
  "dẫn chương trình",
  "dịch thuật",
  "dịch tài liệu",
  "dự toán công trình",
  "ecommerce",
  "email marketing",
  "eplan",
  "erp",
  "etabs",
  "facebook ads",
  "figma",
  "firebase",
  "firewall",
  "flask",
  "flutter",
  "fmea",
  "frontend",
  "fullstack",
  "gcp",
  "giao dịch viên",
  "git",
  "giám sát công trình",
  "giảng dạy",
  "glp",
  "gmp",
  "go",
  "google ads",
  "google analytics",
  "graphic design",
  "graphql",
  "haccp",
  "hardhat",
  "hmi",
  "hrm",
  "html",
  "huy động vốn",
  "hvac",
  "hành chính văn phòng",
  "hóa hữu cơ",
  "hóa phân tích",
  "hóa polymer",
  "hóa sinh",
  "hóa vô cơ",
  "hướng dẫn viên",
  "hạch toán",
  "ids",
  "illustrator",
  "inventor",
  "inverter",
  "ios",
  "ips",
  "iso",
  "java",
  "javascript",
  "journalism",
  "kaizen",
  "keras",
  "kinh doanh",
  "kiểm nghiệm thực phẩm",
  "kiểm soát chất lượng",
  "kiểm toán",
  "kiểm tra chứng từ",
  "kiểm tra hợp đồng",
  "kotlin",
  "kubernetes",
  "kê khai thuế",
  "kế toán bán hàng",
  "kế toán công nợ",
  "kế toán kho",
  "kế toán nội bộ",
  "kế toán thuế",
  "kế toán tổng hợp",
  "kỹ sư xây dựng",
  "kỹ thuật di truyền",
  "kỹ thuật mỏ",
  "kỹ thuật nuôi cấy tế bào",
  "kỹ thuật nuôi cấy vi sinh vật",
  "kỹ thuật protein",
  "laravel",
  "laser",
  "layout design",
  "lead generation",
  "lean",
  "linux",
  "livestream",
  "llm",
  "luật doanh nghiệp",
  "luật lao động",
  "luật thương mại",
  "luật đất đai",
  "luật đầu tư",
  "lăn kim",
  "lấy mụn",
  "lễ tân",
  "lữ hành",
  "machine learning",
  "manual testing",
  "marketing online",
  "massage",
  "may công nghiệp",
  "media buying",
  "mesotherapy",
  "microservices",
  "miễn dịch học",
  "mongodb",
  "motion graphic",
  "mysql",
  "nghiên cứu công thức",
  "nghiên cứu thị trường",
  "nghiệp vụ sư phạm",
  "ngân hàng điện tử",
  "nlp",
  "nodejs",
  "numpy",
  "nuôi cấy tế bào",
  "nuôi cấy vi sinh vật",
  "nối mi",
  "pandas",
  "payroll",
  "peel da",
  "performance marketing",
  "performance testing",
  "pha chế",
  "phay",
  "phi kim",
  "phiên dịch",
  "photoshop",
  "php",
  "phun mày",
  "phun môi",
  "phun xăm",
  "phân tích dinh dưỡng",
  "phân tích mẫu",
  "phân tích thị trường",
  "phân tích đầu tư",
  "phối cảnh",
  "phụ bếp",
  "phục vụ bàn",
  "pif",
  "pipeline management",
  "plc",
  "postgresql",
  "postman",
  "pr",
  "premiere",
  "public relations",
  "python",
  "pytorch",
  "qa",
  "qc",
  "quay dựng",
  "quyết toán thuế",
  "quản lý bếp",
  "quản lý ca",
  "quản lý công trình",
  "quản lý dự án",
  "quản lý hóa đơn",
  "quản lý hồ sơ pháp lý",
  "quản lý hợp đồng lao động",
  "quản lý kho",
  "quản lý khách sạn",
  "quản lý lớp học",
  "quản lý nhà hàng",
  "quản lý nhân sự",
  "quản lý phòng",
  "quản lý rủi ro",
  "quản lý sản xuất",
  "quản lý sự kiện",
  "quản lý vận hành",
  "quản trị mạng",
  "react",
  "red team",
  "redis",
  "rest api",
  "retail sales",
  "revit",
  "robot",
  "ruby",
  "safe",
  "sap",
  "sap2000",
  "scada",
  "scala",
  "scrum",
  "security testing",
  "selenium",
  "sem",
  "sensor",
  "seo",
  "servo",
  "shop drawing",
  "siem",
  "sinh học phân tử",
  "sinh học tế bào",
  "site engineer",
  "six sigma",
  "siêu âm",
  "sketchup",
  "skin care",
  "smart contract",
  "soc",
  "social media",
  "soi da",
  "solidity",
  "solidworks",
  "sop",
  "soạn giáo trình",
  "soạn giáo án",
  "soạn thảo hợp đồng",
  "spring",
  "sql server",
  "sqlite",
  "ssl",
  "ssops",
  "storytelling",
  "supply chain",
  "swift",
  "sắp xếp lịch làm việc",
  "sử dụng thiết bị phòng thí nghiệm",
  "sửa chữa máy móc",
  "sửa chữa điện",
  "sửa chữa động cơ",
  "telesales",
  "tensorflow",
  "testcase",
  "thiết kế 2d",
  "thiết kế bài giảng",
  "thiết kế giao diện",
  "thiết kế kiến trúc",
  "thiết kế mẫu thời trang",
  "thiết kế nội thất",
  "thiết kế rập",
  "thiết kế slide",
  "thiết kế đồ họa",
  "thêu",
  "thông dịch",
  "thẩm định giá",
  "thẩm định hồ sơ",
  "thẩm định tín dụng",
  "thủ tục pháp lý",
  "tiktok ads",
  "tiêm",
  "tiêm filler",
  "tiếng anh",
  "tiếng hàn",
  "tiếng nhật",
  "tiếng pháp",
  "tiếng trung",
  "tiếp nhận cuộc gọi",
  "tiện",
  "tls",
  "triệt lông",
  "truffle",
  "truyền dịch",
  "trực hotline",
  "tuyển dụng",
  "typescript",
  "typography",
  "tìm kiếm khách hàng",
  "tư vấn bảo hiểm",
  "tư vấn bất động sản",
  "tư vấn khách hàng",
  "tư vấn pháp lý",
  "tố tụng",
  "tối ưu hoạt động kỹ thuật",
  "tự động hóa",
  "ui/ux",
  "vi sinh",
  "video editing",
  "vpn",
  "vue",
  "vận hành máy móc",
  "vắt sổ",
  "web3",
  "wireframe",
  "wireshark",
  "x quang",
  "xu hướng thời trang",
  "xây dựng thương hiệu tuyển dụng",
  "xét nghiệm",
  "xử lý công văn",
  "xử lý giao dịch",
  "xử lý khiếu nại",
  "xử lý nợ",
  "điều dưỡng",
  "điều hành tour",
  "điện công nghiệp",
  "điện dân dụng",
  "đánh giá ứng viên",
  "đứng lớp",
];

// =====================================================
// 2. DÁN BÍ DANH / ALIAS VÀO ĐÂY
// =====================================================
const ALIASES = {
  "edit ảnh": "chỉnh sửa ảnh",
  "edit video": "chỉnh sửa video",
  mc: "dẫn chương trình",
  hsk: "tiếng trung",
  n3: "tiếng nhật",
  korean: "tiếng hàn",
  jlpt: "tiếng nhật",
  n1: "tiếng nhật",
  n2: "tiếng nhật",
  n4: "tiếng nhật",
  n5: "tiếng nhật",
  topik: "tiếng hàn",
  ml: "machine learning",
  ai: "machine learning",
  reactjs: "react",
  "react.js": "react",
  "business analyst": "ba",
  node: "nodejs",
  "node.js": "nodejs",
  vuejs: "vue",
  js: "javascript",
  ts: "typescript",
  "restful api": "rest api",
  "fb ads": "facebook ads",
  "gg ads": "google ads",
  "chăm sóc khách hàng": "customer service",
  cskh: "customer service",
  "tiếng anh": "english",
  toeic: "english",
  ielts: "english",
  b1: "english",
  b2: "english",
  c1: "english",
  c2: "english",
  "khả năng lãnh đạo": "leadership",
  "kĩ năng lãnh đạo": "leadership",
  "ui/ux": "ui ux",
  "ux/ui": "ui ux",
  "tuyển dụng": "recruitment",
  accounting: "kế toán",
  xnk: "xuất nhập khẩu",
};

// =====================================================
// 3. DEGREE GIỐNG FILE PYTHON CŨ
// =====================================================
const DEGREE_KEYWORDS = {
  "trung cấp": "degree_trung_cap",
  "cao đẳng": "degree_cao_dang",
  "đại học": "degree_dai_hoc",
  "cử nhân": "degree_cu_nhan",
  bachelor: "degree_cu_nhan",
  "thạc sĩ": "degree_thac_si",
  master: "degree_thac_si",
  "tiến sĩ": "degree_tien_si",
  phd: "degree_tien_si",
};

// =====================================================
// 4. UTILS
// =====================================================
function escapeRegex(text) {
  return String(text).replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function normalizeSkill(skill) {
  const value = String(skill || "")
    .toLowerCase()
    .trim();
  return ALIASES[value] || value;
}

function containsWord(text, word) {
  const regex = new RegExp(
    `(^|[^\\p{L}\\p{N}_])${escapeRegex(word)}([^\\p{L}\\p{N}_]|$)`,
    "iu",
  );

  return regex.test(text);
}

// =====================================================
// 5. EXTRACT JOB INFO
// Trả về:
// {
//   skills: [...],
//   degree: "degree_dai_hoc"
// }
// =====================================================
function extractJobInfo(text = "") {
  if (!text) {
    return {
      skills: [],
      degree: null,
    };
  }

  const normalizedText = String(text).toLowerCase();
  const foundSkills = new Set();

  let degree = null;

  // 1. Detect alias trước
  for (const [alias, canonical] of Object.entries(ALIASES)) {
    if (containsWord(normalizedText, alias)) {
      foundSkills.add(canonical);
    }
  }

  // 2. Detect skill chính
  for (const skill of SKILLS) {
    if (containsWord(normalizedText, skill)) {
      foundSkills.add(normalizeSkill(skill));
    }
  }

  // 3. Detect degree
  for (const [keyword, degreeCode] of Object.entries(DEGREE_KEYWORDS)) {
    if (normalizedText.includes(keyword)) {
      degree = degreeCode;
      break;
    }
  }

  return {
    skills: Array.from(foundSkills).sort(),
    degree,
  };
}

// =====================================================
// 6. HELPER NHẬN VÀO JOB OBJECT
// Dùng cho bảng jobs của bạn:
// name + description + job_requirement
// =====================================================
function extractJobInfoFromJob(job = {}) {
  const text = [
    job.name || "",
    job.description || "",
    job.job_requirement || "",
  ]
    .filter(Boolean)
    .join(" ");

  return extractJobInfo(text);
}

module.exports = {
  extractJobInfo,
  extractJobInfoFromJob,
  normalizeSkill,
};
